/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Display2.C
**     Project   : contador_12_06_06
**     Processor : MC9S12GC16CFU16
**     Beantype  : ByteIO
**     Version   : Bean 02.046, Driver 03.05, CPU db: 2.87.320
**     Compiler  : Metrowerks HC12 C Compiler
**     Date/Time : 18/04/2008, 09:24 a.m.
**     Abstract  :
**         This bean "ByteIO" implements an one-byte input/output.
**         It uses one 8-bit port.
**         Note: This bean is set to work in Output direction only.
**         Methods of this bean are mostly implemented as a macros 
**         (if supported by target langauage and compiler).
**     Settings  :
**         Port name                   : B
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         8-bit data register         : PORTB     [1]
**         8-bit control register      : DDRB      [3]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    16   |   PB0_ADDR0_DATA0
**                    1      |    17   |   PB1_ADDR1_DATA1
**                    2      |    18   |   PB2_ADDR2_DATA2
**                    3      |    19   |   PB3_ADDR3_DATA3
**                    4      |    20   |   PB4_ADDR4_DATA4
**                    5      |    21   |   PB5_ADDR5_DATA5
**                    6      |    22   |   PB6_ADDR6_DATA6
**                    7      |    23   |   PB7_ADDR7_DATA7
**             ----------------------------------------------------
**     Contents  :
**         PutVal - void Display2_PutVal(byte Val);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2004
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

/* MODULE Display2. */

#include "Display2.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG Display2_DATA                                            
#pragma CODE_SEG Display2_CODE                     
#pragma CONST_SEG Display2_CONST       /* Constant section for this module */
/*
** ===================================================================
**     Method      :  Display2_PutVal (bean ByteIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 255)
**     Returns     : Nothing
** ===================================================================
*/
/*
void Display2_PutVal(byte Val)

**  This method is implemented as a macro. See Display2.h file.  **
*/


/* END Display2. */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.95.01 [03.62]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
