/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : TmDt1.H
**     Project   : _7_11
**     Processor : MC9S12GC32CFU16
**     Beantype  : TimeDate
**     Version   : Bean 02.043, Driver 01.09, CPU db: 2.87.320
**     Compiler  : Metrowerks HC12 C Compiler
**     Date/Time : 07/12/2005, 08:34 a.m.
**     Abstract  :
**         This bean "TimeDate" implements real time and date.
**         The bean requires a periodic interrupt generator: timer
**         compare or reload register or timer-overflow interrupt
**         (of free running counter). User can select precision of
**         selected timer.
**         The bean supports also alarm with event OnAlarm.
**     Settings  :
**         Timer name                  : TIM (16-bit)
**
**         Counter                     : TCNT      [68]
**         Mode register               : TIOS      [64]
**         Run register                : TSCR1     [70]
**         Prescaler                   : TSCR2     [77]
**         Compare register            : TC2       [84]
**         Flip-flop register          : TCTL2     [73]
**
**         Interrupt name              : Vtimch2 
**         Interrupt enable reg.       : TIE       [76]
**         Priority                    : 1
**         User handling procedure     : TmDt1_OnAlarm
**         This event is called whenever the current time is equal
**         to alarm time
**
**         High speed mode
**             Prescaler               : divide-by-128
**             Clock                   : 195312 Hz
**           Resolution of timer
**             Xtal ticks              : 2684314
**             microseconds            : 335539
**             milliseconds            : 336
**             seconds (real)          : 0.3355392
**             Hz                      : 3
**
**         Initialization:
**              Timer                  : Disabled
**
**              Time                   : 0:0:0
**              Date                   : 1/1/2001
**     Contents  :
**         Enable   - byte TmDt1_Enable(void);
**         SetTime  - byte TmDt1_SetTime(byte Hour,byte Min,byte Sec,byte Sec100);
**         GetTime  - byte TmDt1_GetTime(TIMEREC *Time);
**         SetDate  - byte TmDt1_SetDate(word Year,byte Month,byte Day);
**         GetDate  - byte TmDt1_GetDate(DATEREC *Date);
**         GetDay   - byte TmDt1_GetDay(byte *Day);
**         SetAlarm - byte TmDt1_SetAlarm(byte Hour,byte Min,byte Sec,byte Sec100);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2004
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef __TmDt1
#define __TmDt1

/* MODULE TmDt1. */
#include <limits.h>
#include "Object.h"
#include "PE_Types.h"


#pragma CODE_SEG TmDt1_CODE                     

typedef struct { /* It contains actual number of hours, minutes, seconds and hundreths of seconds. */
  byte Hour; /* hours (0 - 23) */
  byte Min; /* minutes (0 - 59) */
  byte Sec; /* seconds (0 - 59) */
} TIMEREC;


typedef struct { /* It contains actual year, month, and day description. */
  word Year; /* years (1998 - 2099) */
  byte Month; /* months (1 - 12) */
  byte Day; /* days (1 - 28/31) */
} DATEREC;


struct TmDt1Class{
  struct Class super;
  void(*getTime)(void * self,TIMEREC *time);
  byte (*setTime)(void * self,byte hour,byte min,byte secs);
  void (*getDate)(void * self,DATEREC *date);
  byte (*setDate)(void * self,word year,byte month,byte day);
};

#define TMDT1_CLASS_INITIALIZATION(description,name,super,contructor,destructor,differ,puto,getTime,setTime,getDate,setDate)\
  CLASS_INITIALIZATION(description,name,super,contructor,destructor,differ,puto),\
  getTime,  \
  setTime,  \
  getDate,  \
  setDate
  
struct TmDt1{  
  struct Object super;
  byte CntDay;                    /* Day counter */
  byte CntMonth;                  /* Month counter */
  word CntYear;                   /* Year Counter */
  dword TotalHthL;                
};


extern const struct Class TmDt1Class;
extern const struct TmDt1Class TmDt1; 


//void newObj(void * self,word ,int Month,int Day,int Hour,int Min);
void TmDt1_Constructor(void * self,word Year,byte Month,byte Day,byte Hour,byte Min,byte secs);
/*
** ===================================================================
**     Method      :  TmDt1_Constructor (bean TimeDate)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/

void getTime(void * self,TIMEREC *time);
byte setTime(void * self,byte hour,byte min,byte secs);
byte super_setTime(const struct TmDt1Class*class,void * self,byte hour,byte min,byte secs);
void getDate(void * self,DATEREC *date);
byte setDate(void * self,word year,byte month,byte day);
byte super_setDate(const struct TmDt1Class*class,void * self,word year,byte month,byte day);
/*
** ===================================================================
**     Methodos virtuales
** ===================================================================
*/  
  

byte TmDt1_SetTime(void * self,byte Hour,byte Min,byte secs);
/*
** ===================================================================
**     Method      :  TmDt1_SetTime (bean TimeDate)
**
**     Description :
**         Sets a new actual time.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Hour            - Hours (0 - 23)
**         Min             - Minutes (0 - 59)
**         Sec             - Seconds (0 - 59)
**         Sec100          - Hundredths of seconds (0 - 99)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/

void TmDt1_GetTime(void * self,TIMEREC *Time);
/*
** ===================================================================
**     Method      :  TmDt1_GetTime (bean TimeDate)
**
**     Description :
**         Return current time.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Time            - Pointer to the structure TIMEREC. It
**                           contains actual number of hours, minutes,
**                           seconds and hundreths of seconds.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

byte TmDt1_SetDate(void * self,word Year,byte Month,byte Day);
/*
** ===================================================================
**     Method      :  TmDt1_SetDate (bean TimeDate)
**
**     Description :
**         Set a new actual date.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Year            - Years (16-bit unsigned integer)
**         Month           - Months (8-bit unsigned integer)
**         Day             - Days (8-bit unsigned integer)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/

byte  TmDt1_GetMaxday(word Year,byte Month);
/*
** ===================================================================
**     Function      :  TmDt1_GetMaxday 
**
**     Description :
**         Retorna la maxima cantidad de dias ara el mes de ese anio
**     Parameters  :
**         Year            - anio
**         Month           - Mes
**     Returns     :
**         maxima cantidad de dias ara el mes de ese anio
**         0							 - Error
** ===================================================================
*/

void TmDt1_GetDate(void * self,DATEREC *Date);

/*
** ===================================================================
**     Method      :  TmDt1_GetDay (bean TimeDate)
**
**     Description :
**         Return current day of the week.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Day             - Pointer to returned day - 8-bit
**                           unsigned number
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
    
void TmDt1_Inc(void * self,dword);                     
/*
** ===================================================================
**     Method      :  TmDt1_Inc 
**
**     Description :
**         
** ===================================================================
*/


#pragma CODE_SEG DEFAULT                                   

/* END TmDt1. */

#endif /* ifndef __TmDt1 */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.95 [03.62]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
