																															/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : TO1.H
**     Project   : _10_03
**     Processor : MC9S12GC32CFU16
**     Beantype  : TimerOut
**     Version   : Bean 02.095, Driver 01.08, CPU db: 2.87.320
**     Compiler  : Metrowerks HC12 C Compiler
**     Date/Time : 24/07/2006, 10:32 a.m.
**     Abstract  :
**         This bean implements a periodic signal generator 1:1 (Flip-Flop Output).
**         The signal alternates the "0" and "1" output values in exactly
**         regular intervals; that is why the time length of the "0" part
**         of one pulse is equal to the "1" part of one pulse.
**     Settings  :
**         Used output pin             : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       6             |  PT1_PWM1_IOC1
**             ----------------------------------------------------
**
**         Timer name                  : TIM (16-bit)
**         Compare name                : TC1
**           Counter shared            : Yes
**
**         High speed mode
**             Prescaler               : divide-by-16
**             Clock                   : 1562500 Hz
**           Pulse width
**             Xtal ticks              : 31
**             microseconds            : 4
**             seconds (real)          : 0.0000038
**             Hz                      : 260417
**             kHz                     : 260
**
**         Runtime setting             : pulse width interval (continual setting)
**             ticks                   : 31 to 320000 ticks
**             microseconds            : 4 to 40000 microseconds
**             milliseconds            : 1 to 40 milliseconds
**             seconds (real)          : 0.0000038 to 0.0400000 seconds
**             Hz                      : 25 to 260416 Hz
**             kHz                     : 1 to 260 kHz
**
**         Initialization:
**              Output level           : low
**              Timer                  : Disabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : TCNT      [68]
**              Mode                   : TIOS      [64]
**              Run                    : TSCR1     [70]
**              Prescaler              : TSCR2     [77]
**
**         Compare registers
**              Compare                : TC1       [82]
**
**         Flip-flop registers
**              Mode                   : TCTL2     [73]
**     Contents  :
**         Enable      - byte TO1_Enable(void);
**         Disable     - byte TO1_Disable(void);
**         SetPeriodUS - byte TO1_SetPeriodUS(word Time);
**         SetValue    - byte TO1_SetValue(void);
**         ClrValue    - byte TO1_ClrValue(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2004
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef __TO1
#define __TO1

/* MODULE TO1. */

#include "Cpu.h"

#pragma CODE_SEG PWM_CODE                     
#pragma DATA_SEG PWM_DATA                                            

/* Constants for period mode */
typedef enum{
  PWM_100ms       =0,         /* Constant for switch to mode 0 */
  PWM_200ms       =1,         /* Constant for switch to mode 1 */
  PWM_500ms       =2,         /* Constant for switch to mode 2 */
  PWM_1sec        =3,         /* Constant for switch to mode 3 */
  PWM_2sec        =4,         /* Constant for switch to mode 4 */
  PWM_5sec        =5,         /* Constant for switch to mode 5 */
  PWM_10sec       =6,         /* Constant for switch to mode 6 */
  PWM_20sec       =7,         /* Constant for switch to mode 7 */
  PWM_50sec       =8,         /* Constant for switch to mode 8 */
  PWM_Anl         =9					/* Constant for switch to mode 9 */
}TPeriod;	 /* Data type for select modes */

#define PWM_Last_Period 9

byte PWM_SetRatio16(word Ratio,byte salida);		/*Ratio es un valor de 0 a 1000*/
byte setPWM_period(int Mode,byte salida);

/*
** ===================================================================
**     Method      :  TO1_SetPeriod (bean TimerOut)
**
**     Description :
**         This method sets the new period of the output signal. The
**         period is expressed in microseconds as a 16-bit unsigned
**         integer number.
**         This method is available only if the runtime setting type
**         'from interval' is selected in the Timing dialog box in
**         the Runtime setting area.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Time            - Period to set [in microseconds]
**                      (4 to 40000 microseconds)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_MATH - Overflow during evaluation
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/


#pragma CODE_SEG __NEAR_SEG NON_BANKED     
__interrupt void PWM_Interrupt(void);
__interrupt void PWM4_Interrupt(void);
__interrupt void PWM5_Interrupt(void);
__interrupt void PWM6_Interrupt(void);
#pragma CODE_SEG PWM_CODE                     
/*
** ===================================================================
**     Method      :  TO1_Interrupt (bean TimerOut)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/

void PWM_Init(void);
#define PWM4_Init() {}
#define PWM5_Init() {}
#define PWM6_Init() {}
/*
** ===================================================================
**     Method      :  TO1_Init (bean TimerOut)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/

#pragma DATA_SEG DEFAULT                                  
#pragma CODE_SEG DEFAULT                                   

/* END TO1. */

#endif /* ifndef __TO1 */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.95 [03.62]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
