/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : ADC1.C
**     Project   : _7_12
**     Processor : MC9S12GC32CFU16
**     Beantype  : Init_ADC
**     Version   : Bean 01.079, Driver 01.02, CPU db: 2.87.320
**     Compiler  : Metrowerks HC12 C Compiler
**     Date/Time : 14/12/2005, 09:44
**     Abstract  :
**          This file implements the ADC (ADC0) module initialization
**          according to the Peripheral Initialization Bean settings,
**          and defines interrupt service routines prototypes.The ADC module
**          is an 8-channel (16-channel), 10-bit, multiplexed input successive
**          approximation analog-to-digital converter. Refer to device electrical
**          specifications for ATD accuracy. The block is designed to be 
**          upwards compatible with the 68HC11 standard 8-bit A/D converter.
**          In addition, there are new operating modes that are unique to 
**          the HC12 design.
**          Features :
**          - 8/10 Bit Resolution.
**          - 7msec, 10-Bit Single Conversion Time.
**          - Sample Buffer Amplifier.
**          - Programmable Sample Time.
**          - Left/Right Justified, Signed/Unsigned Result Data.
**          - External Trigger Control.
**          - Conversion Completion Interrupt Generation.
**          - Analog Input Multiplexer for 8 (16)Analog Input Channels.
**          - Analog/Digital Input Pin Multiplexing.
**          - 1 to 8 (1 to 16)Conversion Sequence Lengths.
**          - Continuous Conversion Mode.
**          - Multiple Channel Scans.
**     Comment   :
**         sacar setReg8 ( ATD0TL5, XXX);
**     Settings  :
**          Bean name                                      : ADC1
**          Device                                         : ADC0
**          Sample Time                                    : 16 A/D conversion clock periods
**          Prescaler                                      : 3
**          Frequency                                      : 500 kHz
**          Channel select code                            : AN0
**          Channel select code                            : AN0
**          Conv. sequence length                          : 4
**          Conv. sequence length                          : 8
**          Conversion mode                                : Single conversion
**          Channel sample mode                            : Only one channel
**          Fast flag clear all                            : Enabled
**          Wrap around channel                            : AN15
**          External trigger source                        : AN15
**          Wrap around channel                            : AN7
**          External trigger source                        : AN7
**          External trigger                               : Disabled
**          External trigger control                       : Falling edge
**          Conv. results are placed in                    : Corresponding result register
**          Result data formats                            : 10-bit/right justified/unsigned
**          Background debug freeze                        : Freeze Immediately
**          Special channel conversion                     : Disabled
**          Power down in Wait mode                        : Enabled
**          AN0                                            : Disabled
**          AN1                                            : Disabled
**          AN2                                            : Disabled
**          AN3                                            : Disabled
**          AN4                                            : Disabled
**          AN5                                            : Enabled
**          Pin                                            : PAD05_AN05
**          Pin Signal                                     : 
**          Digital Input                                  : Disabled
**          AN6                                            : Enabled
**          Pin                                            : PAD06_AN06
**          Pin Signal                                     : 
**          Digital Input                                  : Disabled
**          ETRIG/AN7                                      : Disabled
**          AN7                                            : Disabled
**          AN8                                            : Disabled
**          AN9                                            : Disabled
**          AN10                                           : Disabled
**          AN11                                           : Disabled
**          AN12                                           : Disabled
**          AN13                                           : Disabled
**          AN14                                           : Disabled
**          ETRIG/AN15                                     : Disabled
**          AN15                                           : Disabled
**          Sequence Complete                              : Enabled
**          Interrupt                                      : Vatd0
**          Priority                                       : maximal priority
**          ISR name                                       : ADC_Interrupt
**          Call Init in CPU init. code                    : yes
**          Module                                         : Enabled
**     Contents  :
**         Init - void ADC1_Init(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2004
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

/* MODULE ADC1. */

#include "ADC1.h"

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      _7_12.c
**      RTI.c
**      TmDt1.c
**      Linealizacion.c
**      PWMs.c
**      Comunicacion.c
**      ADC.c
**      teclas2.c
**      display.c
**
** ###################################################################
#pragma CODE_SEG __NEAR_SEG NON_BANKED     
ISR(ADC_Interrupt)
        {
        // NOTE: The routine should include the following actions to obtain
        //       correct functionality of the hardware.
        //
        //      The interrupt will remain pending as long as the ASCIF (SCF) flag is set.
        //      The ASCIF (SCF) bit is cleared whenever the ATDCTL5 register is written.
        //      The ASCIF (SCF) bit is also cleared whenever the SCF bit is written.
        //      And the third case is whenever AFFC bit is set and read of a result register.
        //      Example: SCF = 1;
        }
#pragma CODE_SEG DEFAULT                                   
*/
/*
** ===================================================================
**     Method      :  ADC1_Init (bean Init_ADC)
**
**     Description :
**         This method initializes registers of the ADC module
**         according to this Peripheral Initialization Bean settings.
**         Call this method in user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the bean for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void ADC1_Init(void)
{
  /* ATDCTL3: ??=0,S8C=0,S4C=0,S2C=0,S1C=0,FIFO=0,FRZ1=1,FRZ0=1 */
  setReg8(ATDCTL3, 3);                  
  /* ATDCTL4: SRES8=0,SMP1=1,SMP0=1,PRS4=0,PRS3=0,PRS2=0,PRS1=1,PRS0=1 */
  setReg8(ATDCTL4, 99);                 
  /* ATDCTL5: DJM=1,DSGN=0,SCAN=0,MULT=0,??=0,CC=0,CB=0,CA=0 */
  //setReg8(ATDCTL5, 128);                
  /* ATDTEST1: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,SC=0 */
  setReg8(ATDTEST1, 0);                 
  /* ATDDIEN: IEN7=0,IEN6=0,IEN5=0,IEN4=0,IEN3=0,IEN2=0,IEN1=0,IEN0=0 */
  setReg8(ATDDIEN, 0x9F);                  
  /* ATDCTL2: ADPU=1,AFFC=1,AWAI=1,ETRIGLE=0,ETRIGP=0,ETRIGE=0,ASCIE=1,ASCIF=0 */
  setReg8(ATDCTL2, 226);                
  setReg8(HPRIO, 210);                  
}

/* END ADC1. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.95 [03.62]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
