/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : EI2C1.C
**     Project   : Project_2
**     Processor : MC9S12GC32CFU16
**     Beantype  : SW_I2C
**     Version   : Bean 01.119, Driver 03.22, CPU db: 2.87.392
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 5/4/2009, 11:47 PM
**     Abstract  :
**         This device "SW_I2C" implements an external I2C
**         communication interface. It uses two general-purpose
**         I/O pins.
**     Settings  :
**         Serial Clock (SCL) pin      :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       3             |  PP1_PWM1_KWP1 (opcion 1)
**                       52                             (opcion 2)
**             ----------------------------------------------------
**
**         Serial Data (SDA) pin       :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       79            |  PP5_PWM5_KWP5  (opcion 1)
**                       51                              (opcion 2)
**             ----------------------------------------------------
**
**
**         Mode                        : MASTER
**         Communication Speed         : STANDARD MODE
**         Output Buffer Size          : 0
**         Auto Stop Condition         : no
**         Acknowledge Polling Trials  : 2000
**
**         Speed modes
**
**             High Speed Mode         : Enabled
**             Low Speed Mode          : Disabled
**             Slow Speed Mode         : Disabled
**
**         Initialization
**
**             Slave address           : 104
**             Bean function           : Enabled
**             Events                  : Enabled
**     Contents  :
**         SendChar  - byte EI2C1_SendChar(byte Chr);
**         RecvChar  - byte EI2C1_RecvChar(byte *Chr);
**         SendBlock - byte EI2C1_SendBlock(void* Ptr, word Siz, word *Snt);
**         RecvBlock - byte EI2C1_RecvBlock(void* Ptr, word Siz, word *Rcv);
**         SendStop  - byte EI2C1_SendStop(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2007
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/


/* MODULE EI2C1. */

#include "Events.h"
#include "PE_Error.h"
#include "EI2C1.h"
#include "Inhr2.h"
#include "Inhr1.h"
#include "BaseTiempoDS1307.h"

#pragma DATA_SEG EI2C1_DATA
#pragma CODE_SEG EI2C1_CODE

#define ACK         0
#define NOACK       1
#define OUTPUT      1
#define INPUT       0
#define WRITE       0
#define READ        1
#define TRIALS      2000

static byte SlaveAddr;             /* destination slave address      */

/* Internal method prototypes */
/*
** ===================================================================
**     Method      :  EI2C1_Delay (bean SW_I2C)
**
**     Description :
**         The method waits in delay loop.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#pragma CODE_SEG __NEAR_SEG NON_BANKED
#pragma NO_ENTRY
#pragma NO_EXIT
static void Delay(void)
{
  asm {
    /* jsr/bsr                            (4 c) jump/branch to subroutine */
    /*
     * Delay
     *   - requested                  : 5000 ns @ 16MHz,
     *   - possible                   : 80 c, 5000 ns
     *   - without removable overhead : 71 c, 4437.5 ns
     */
    pshd                               /* (2 c: 125 ns) backup D */
    ldd #21                            /* (2 c: 125 ns) number of iterations */
    label0:
    dbne d, label0                     /* (3 c: 187.5 ns) repeat 21x */
    puld                               /* (3 c: 187.5 ns) restore D */
    nop                                /* (1 c: 62.5 ns) wait for 1 c */
    rts                                /* (5 c) return from subroutine */
  }
}
#pragma CODE_SEG EI2C1_CODE


/*
** ===================================================================
**     Method      :  EI2C1_Init (bean SW_I2C)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void EI2C1_Init(void)
{
#ifdef opcion_1
  clrReg8Bits(PIEP, 34);                
  /* PTP: PTP5=1,PTP1=1 */
  setReg8Bits(PTP, 34);                 
  /* PPSP: PPSP5=0,PPSP1=0 */
  clrReg8Bits(PPSP, 34);                
  /* PERP: PERP5=1,PERP1=1 */
  setReg8Bits(PERP, 34);                
  /* DDRP: DDRP5=0,DDRP1=0 */
  clrReg8Bits(DDRP, 34);     
#else  
  setReg8Bits(PTAD,3);          
  clrReg8Bits(PPSAD,3);      
  setReg8Bits(PERAD,3);            
  clrReg8Bits(DDRAD,3);
#endif  
  
  SlaveAddr = 208;
}

/*
** ===================================================================
**     Method      :  EI2C1_Write (bean SW_I2C)
**
**     Description :
**         The method sends one byte of data to the bus.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void Write(byte Data)
{
  byte Shift;
  byte I;
  word timeout;

  Shift = 128;
  for (I = 8; I != 0; I--) {
    if (Data & Shift) {
      Inhr1_SetDir((bool)INPUT);   /* SDA HIGH */
    }
    else {
      Inhr1_SetDir((bool)OUTPUT);
      Inhr1_ClrVal();              /* SDA LOW */
    }
    Shift >>= 1;
    Inhr2_SetDir((bool)INPUT);     /* CLOCK HIGH PULSE */
    Delay();
    timeout = 65535;
    while((Inhr2_GetVal()==0)&&(timeout!=0)) { /* WAIT FOR CLOCK HIGH PULSE */
      timeout--;
    }
    Inhr2_SetDir((bool)OUTPUT);
    Inhr2_ClrVal();                /* CLOCK LOW PULSE */
    Delay();
  }
}

/*
** ===================================================================
**     Method      :  EI2C1_Read (bean SW_I2C)
**
**     Description :
**         The method reads one byte of data from the bus.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static byte Read(void)
{
  byte Shift;
  byte I;
  word timeout;

  Shift = 0;
  Inhr1_SetDir((bool)INPUT);       /* SDA INPUT MODE */
  for (I = 8; I != 0; I--) {
    Inhr2_SetDir((bool)INPUT);     /* CLOCK HIGH PULSE */
    Delay();
    timeout = 65535;
    while((Inhr2_GetVal()==0)&&(timeout!=0)) { /* WAIT FOR CLOCK HIGH PULSE */
      timeout--;
    }
    Shift <<= 1;
    if (Inhr1_GetVal()) {
      Shift++;
    }
    Inhr2_SetDir((bool)OUTPUT);
    Inhr2_ClrVal();                /* CLOCK LOW PULSE */
    Delay();
  }
  return Shift;
}

/*
** ===================================================================
**     Method      :  EI2C1_GetAck (bean SW_I2C)
**
**     Description :
**         The method reads ACK from the bus.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static bool GetAck(void)
{
  word timeout;

  Inhr1_SetDir((bool)INPUT);       /* SDA HIGH */
  Inhr2_SetDir((bool)INPUT);       /* CLOCK HIGH PULSE */
  Delay();
  timeout = 65535;
  while((Inhr2_GetVal()==0)&&(timeout!=0)) { /* WAIT FOR CLOCK HIGH PULSE */
    timeout--;
  }
  return((bool)Inhr1_GetVal());    /* ACKNOWLEDGE VALUE */
}

/*
** ===================================================================
**     Method      :  EI2C1_SetAck (bean SW_I2C)
**
**     Description :
**         The method sends ACK to the bus.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void SetAck(bool Ack)
{
  word timeout;

  if (Ack) {
    Inhr1_SetDir((bool)INPUT);     /* MASTER NOACKNOWLEDGE - SDA HIGH */
  }
  else {
    Inhr1_SetDir((bool)OUTPUT);
    Inhr1_ClrVal();                /* MASTER ACKNOWLEDGE - SDA LOW */
  }
  Inhr2_SetDir((bool)INPUT);       /* HIGH CLOCK PULSE */
  Delay();
  timeout = 65535;
  while((Inhr2_GetVal()==0)&&(timeout!=0)) { /* WAIT FOR CLOCK HIGH PULSE */
    timeout--;
  }
  Inhr2_SetDir((bool)OUTPUT);
  Inhr2_ClrVal();                  /* LOW CLOCK PULSE */
  Delay();
  Inhr1_SetDir((bool)INPUT);       /* ACKNOWLEDGE END - SDA HIGH  */
}


/*
** ===================================================================
**     Method      :  EI2C1_InternalStop (bean SW_I2C)
**
**     Description :
**         The method generates the Stop condition on the bus.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void InternalStop(void)
{
  Inhr1_SetDir((bool)OUTPUT);
  Inhr1_ClrVal();                  /* STOP SETUP */
  Inhr2_SetDir((bool)INPUT);       /* CLOCK HIGH PULSE + STOP SETUP TIME */
  Delay();
  Inhr1_SetDir((bool)INPUT);       /* STOP CONDITION */
}



/*
** ===================================================================
**     Method      :  EI2C1_SendChar (bean SW_I2C)
**
**     Description :
**         When working as a MASTER, this method writes 7 bits of slave
**         address plus R/W bit = 0 to the I2C bus and then writes one
**         character (byte) to the bus. The slave address must be
**         specified before by the "SelectSlave" method or in the bean
**         initialization section of <Slave address init> property.
**         When working as the SLAVE, this method writes one character
**         (byte) to the bus. If the ERR_NOTAVAIL error code returned,
**         the char is successfully sent to master but the master
**         device responds by an acknowledgement instead of no
**         acknowledgement at the end of transfer. <OnError> event is
**         called in this case.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_BUSY - The slave device is busy, it
**                           does not respond by the acknowledgement
**                           (MASTER mode only)
**                           ERR_NOTAVAIL - The master device sends
**                           acknowledgement instead of no
**                           acknowledgement after the last byte
**                           transfer (SLAVE mode only)
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSOFF - Clock timeout elapsed (SLAVE
**                           mode only)
** ===================================================================
*/
byte EI2C1_SendChar(byte Chr)
{
  word Trial;
  bool Acknowledge;

  Trial = TRIALS;
  do {
    Inhr1_SetDir((bool)INPUT);     /* SDA HIGH - START SETUP*/
    Inhr2_SetDir((bool)INPUT);     /* CLOCK HIGH PULSE */
    Delay();                       /* CLOCK HIGH PULSE & BUS FREE TIME */
    Inhr1_SetDir((bool)OUTPUT);
    Inhr1_ClrVal();                /* START CONDITION */
    Delay();                       /* START HOLD TIME */
    Inhr2_SetDir((bool)OUTPUT);
    Inhr2_ClrVal();                /* CLOCK LOW PULSE */
    Delay();
    Write((byte)(SlaveAddr + WRITE));
    Acknowledge = GetAck();
    --Trial;
  } while (Trial && Acknowledge);
  if (Acknowledge) {               /* WRONG ACKNOWLEDGE */
    EI2C1_OnNACK();
    Inhr2_SetDir((bool)OUTPUT);
    Inhr2_ClrVal();                /* CLOCK LOW PULSE */
    InternalStop();
    return ERR_BUSY;
  }                           
  else {
    Inhr2_SetDir((bool)OUTPUT);
    Inhr2_ClrVal();                /* CLOCK LOW PULSE */
    Delay();
  }
  Write(Chr);
  if (GetAck()) {                  /* WRONG ACKNOWLEDGE */
    EI2C1_OnNACK();
    Inhr2_SetDir((bool)OUTPUT);
    Inhr2_ClrVal();                /* CLOCK LOW PULSE */
    InternalStop();
    return ERR_BUSY;
  }
  else {
    EI2C1_OnTxChar();
    Inhr2_SetDir((bool)OUTPUT);
    Inhr2_ClrVal();                /* CLOCK LOW PULSE */
    Delay();
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  EI2C1_RecvChar (bean SW_I2C)
**
**     Description :
**         When working as a MASTER, this method writes 7 bits of slave
**         address plus R/W bit = 1 to the I2C bus and then reads one
**         character (byte) from the bus. The slave address must be
**         specified before by the "SelectSlave" method or in the bean
**         initialization section of <Slave address init> property.
**         When working as a SLAVE, this method reads one character
**         (byte) from the bus.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - Pointer to received character
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_BUSY - The slave device is busy, it
**                           does not respond by the acknowledgement
**                           (MASTER mode only)
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSOFF - Clock timeout elapsed (SLAVE
**                           mode only)
** ===================================================================
*/
byte EI2C1_RecvChar(byte *Chr)
{
  word Trial;
  bool Acknowledge;

  Trial = TRIALS;
  do {
    Inhr1_SetDir((bool)INPUT);     /* SDA HIGH - START SETUP */
    Inhr2_SetDir((bool)INPUT);     /* CLOCK HIGH PULSE */
    Delay();                       /* CLOCK HIGH PULSE & BUS FREE TIME */
    Inhr1_SetDir((bool)OUTPUT);
    Inhr1_ClrVal();                /* START CONDITION */
    Delay();                       /* START HOLD TIME */
    Inhr2_SetDir((bool)OUTPUT);
    Inhr2_ClrVal();                /* CLOCK LOW PULSE */
    Delay();
    Write((byte)(SlaveAddr + READ));
    Acknowledge = GetAck();
    --Trial;
  } while (Trial && Acknowledge);
  if (Acknowledge) {
    EI2C1_OnNACK();
    Inhr2_SetDir((bool)OUTPUT);
    Inhr2_ClrVal();                /* CLOCK LOW PULSE */
    InternalStop();
    return ERR_BUSY;
  }
  else {
    Inhr2_SetDir((bool)OUTPUT);
    Inhr2_ClrVal();                /* CLOCK LOW PULSE */
    Delay();
  }
  *Chr = Read();
  EI2C1_OnRxChar();
  SetAck((bool)NOACK);
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  EI2C1_SendBlock (bean SW_I2C)
**
**     Description :
**         When working as a MASTER, this method writes 7 bits of slave
**         address plus R/W bit = 0 to the I2C bus and then writes the
**         block of characters to the bus. If the bean is disabled (by
**         the "Disable" method or initialization), the block is moved
**         to the output buffer if the <Output buffer size> property is
**         different from zero. The content of the output buffer is
**         sent immediately with the stop condition at the end when the
**         bean is enabled by the "Enable" method. After the output
**         buffer transmission, the whole output buffer is cleared. The
**         slave address must be specified before by the "SelectSlave"
**         method or in bean initialization section of <Slave address
**         init> property. When working as a SLAVE, this method writes
**         block of characters to the bus. If the ERR_NOTAVAIL error
**         code is returned, the whole block is successfully sent to a
**         master but the master device responds by an acknowledgement
**         instead of no acknowledgment sent at the end of the last
**         block byte transfer. <OnError> event is called in this case.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - A pointer to the block of data to send
**         Siz             - The size of the block
**       * Snt             - A pointer to the number of data that are
**                           sent (copied to buffer)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_BUSY - The slave device is busy, it
**                           does not respond by the acknowledgement
**                           (MASTER mode only)
**                           ERR_TXFULL - Output buffer is full (MASTER
**                           mode only)
**                           ERR_NOTAVAIL - The master device sends
**                           acknowledgement instead of no
**                           acknowledgement after the last byte
**                           transfer (SLAVE mode only)
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSOFF - Clock timeout elapsed (SLAVE
**                           mode only)
** ===================================================================
*/
byte EI2C1_SendBlock(void* Ptr,word Siz,word *Snt)
{
  register word I;
  bool Acknowledge;
  word Trial;

  *Snt = 0;
  Trial = TRIALS;
  do {
    Inhr1_SetDir((bool)INPUT);     /* SDA HIGH  - START SETUP */
    Inhr2_SetDir((bool)INPUT);     /* CLOCK HIGH PULSE */
    Delay();                       /* CLOCK HIGH PULSE + BUS FREE TIME */
    Inhr1_SetDir((bool)OUTPUT);
    Inhr1_ClrVal();                /* START CONDITION */
    Delay();                       /* START HOLD TIME */
    Inhr2_SetDir((bool)OUTPUT);
    Inhr2_ClrVal();                /* CLOCK LOW PULSE */
    Delay();
    Write((byte)(SlaveAddr + WRITE));
    Acknowledge = GetAck();
    --Trial;
  } while (Trial && Acknowledge);
  if (Acknowledge) {
    EI2C1_OnNACK();
    Inhr2_SetDir((bool)OUTPUT);
    Inhr2_ClrVal();                /* CLOCK LOW PULSE */
    InternalStop();
    return ERR_BUSY;
  }
  else {
    Inhr2_SetDir((bool)OUTPUT);
    Inhr2_ClrVal();                /* CLOCK LOW PULSE */
    Delay();
  }
  for (I = 0; I < Siz; I++) {
    Write ( *((byte *) Ptr + I) );
    if (GetAck()) {
      EI2C1_OnNACK();
      Inhr2_SetDir((bool)OUTPUT);
      Inhr2_ClrVal();              /* CLOCK LOW PULSE */
      InternalStop();
      return ERR_BUSY;
    }
    else {
      EI2C1_OnTxChar();
      Inhr2_SetDir((bool)OUTPUT);
      Inhr2_ClrVal();              /* CLOCK LOW PULSE */
      Delay();
    }
    ++(*Snt);
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  EI2C1_RecvBlock (bean SW_I2C)
**
**     Description :
**         When working as a MASTER, this method writes 7 bits of slave
**         address plus R/W bit = 1 to the I2C bus and then reads the
**         block of characters from the bus. The slave address must be
**         specified before by the "SelectSlave" method or in bean
**         initialization section of <Slave address init> property.
**         When working as a SLAVE, this method reads the block of
**         characters from the bus.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - A pointer to the block space for received
**                           data
**         Siz             - The size of the block
**       * Rcv             - A pointer to the number of actually
**                           received data
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_BUSY - The slave device is busy, it
**                           does not respond by the acknowledgement
**                           (MASTER mode only)
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSOFF - Clock timeout elapsed (SLAVE
**                           mode only)
** ===================================================================
*/
byte EI2C1_RecvBlock(void* Ptr,word Siz,word *Rcv)
{
  register word I;
  bool Acknowledge;
  word Trial;

  *Rcv = 0;
  Trial = TRIALS;
  do {
    Inhr1_SetDir((bool)INPUT);     /* SDA HIGH - START SETUP */
    Inhr2_SetDir((bool)INPUT);     /* CLOCK HIGH PULSE */
    Delay();                       /* CLOCK HIGH PULSE + BUS FREE TIME */
    Inhr1_SetDir((bool)OUTPUT);
    Inhr1_ClrVal();                /* START CONDITION */
    Delay();                       /* START HOLD TIME */
    Inhr2_SetDir((bool)OUTPUT);
    Inhr2_ClrVal();                /* CLOCK LOW PULSE */
    Delay();
    Write((byte)(SlaveAddr + READ));
    Acknowledge = GetAck();
    --Trial;
  } while (Trial && Acknowledge);
  if (Acknowledge) {
    EI2C1_OnNACK();
    Inhr2_SetDir((bool)OUTPUT);
    Inhr2_ClrVal();                /* CLOCK LOW PULSE */
    InternalStop();
    return ERR_BUSY;
  }
  else {
    Inhr2_SetDir((bool)OUTPUT);
    Inhr2_ClrVal();                /* CLOCK LOW PULSE */
    Delay();
  }
  for (I = 0; I < Siz; I++) {
    *((byte *) Ptr + I) = Read();
    EI2C1_OnRxChar();
    if (I == (Siz - 1)) {
      SetAck((bool)NOACK);
    }
    else {
      SetAck((bool)ACK);
    }
    ++(*Rcv);
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  EI2C1_SendStop (bean SW_I2C)
**
**     Description :
**         When working as a MASTER, if the <Automatic stop condition>
**         property value is 'no', this method sends a valid stop
**         condition to the serial data line of the I2C bus to
**         terminate the communication on the bus after using send
**         methods. This method is enabled only if the bean is in
**         MASTER mode and <Automatic stop condition> property value is
**         'no'
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
** ===================================================================
*/
byte EI2C1_SendStop(void)
{
  Inhr1_SetDir((bool)OUTPUT);
  Inhr1_ClrVal();                  /* STOP SETUP */
  Inhr2_SetDir((bool)INPUT);       /* HIGH CLOCK PULSE + STOP SETUP TIME */
  Delay();
  Inhr1_SetDir((bool)INPUT);       /* STOP CONDITION */
  return ERR_OK;
}


/* END EI2C1. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.98 [03.98]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
