/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : bits5ULN.H
**     Project   : _12_10
**     Processor : MC9S12A64BCFU
**     Beantype  : BitsIO
**     Version   : Bean 02.065, Driver 03.04, CPU db: 2.87.268
**     Compiler  : Metrowerks HC12 C Compiler
**     Date/Time : 19/10/2005, 8:56
**     Abstract  :
**         This bean "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This bean is set to work in Output direction only.
**     Settings  :
**         Port name                   : M
**
**         Bit mask of the port        : 63
**         Number of bits/pins         : 6
**         Single bit numbers          : 0 to 5
**         Values range                : 0 to 63
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         Port data register          : PTM       [592]
**         Port control register       : DDRM      [594]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    75   |   PM0
**                    1      |    74   |   PM1
**                    2      |    73   |   PM2_MISO0
**                    3      |    72   |   PM3_SS0
**                    4      |    71   |   PM4_MOSI0
**                    5      |    70   |   PM5_SCK0
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents  :
**         PutVal - void bits5ULN_PutVal(byte Val);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2004
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef bits5ULN_H_
#define bits5ULN_H_

/* MODULE bits5ULN. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma CODE_SEG bits5ULN_CODE                     
/*
** ===================================================================
**     Method      :  bits5ULN_PutVal (bean BitsIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 63)
**     Returns     : Nothing
** ===================================================================
*/
#define bits5ULN_PutVal(Val) setReg8(PTM, Val)          /* BIT0-BIT7=Val[bits 0-7] */ \
  

#pragma CODE_SEG DEFAULT                                   

/* END bits5ULN. */
#endif /* #ifndef __bits5ULN_H_ */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.95 [03.62]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
