/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Puls1.C
**     Project   : contador_12_06_06
**     Processor : MC9S12GC16CFU16
**     Beantype  : PulseAccumulator
**     Version   : Bean 01.093, Driver 01.10, CPU db: 2.87.320
**     Compiler  : Metrowerks HC12 C Compiler
**     Date/Time : 16/01/2008, 09:50 a.m.
**     Abstract  :
**          In event counter mode, a pulse accumulator counts the number of active
**          edges at the input of its channel.
**          Pulse accumulator bean usually cooperates with capture bean on the same
**          channel.
**     Settings  :
**             Pulse accumulator       : PACNT
**
**         Initialization:
**              Mode                   : Event counter
**              Pulse accumulator      : Disabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : PACNT     [98]
**              Mode                   : PACTL     [96]
**              Run                    : PACTL     [96]
**              Edge                   : TCTL4     [75]
**              Prescaler              : PACTL     [96]
**         Overflow interrupt name     : Vtimpaovf
**              Int. enable reg.       : PACTL     [96]
**              Int. request reg.      : PAFLG     [97]
**
**         Edge interrupt name         : Vtimpaie
**              Int. enable reg.       : PACTL     [96]
**         Handling procedure          : Puls1_OnEdge
**
**         Used input pin              :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       14            |  PT7_IOC7
**             ----------------------------------------------------
**
**         Port name                   : T
**         Bit number (in port)        : 7
**         Bit mask of the port        : 128
**
**         Active input signal edge    : rising
**         Pull option                 : off
**
**     Contents  :
**         Enable          - byte Puls1_Enable(void);
**         ResetCounter    - void Puls1_ResetCounter(void);
**         GetCounterValue - word Puls1_GetCounterValue(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2004
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

/* MODULE Puls1. */

#include "Puls1.h"

#pragma DATA_SEG Puls1_DATA                                            
#pragma CODE_SEG Puls1_CODE                     

/*
** ===================================================================
**     Method      :  Puls1_Enable (bean PulseAccumulator)
**
**     Description :
**         Enables the bean.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/
byte Puls1_Enable(void)
{
  PACTL_PAEN = 1;                      /* Enable 16-bit pulse accumulator */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  Puls1_ResetCounter (bean PulseAccumulator)
**
**     Description :
**         This method resets the pulse accumulator counter (sets to
**         zero).
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Puls1_ResetCounter(void)

**      This method is implemented as macro. See Puls1.h file.      **
*/

/*
** ===================================================================
**     Method      :  Puls1_GetCounterValue (bean PulseAccumulator)
**
**     Description :
**         This method returns a content of the pulse accumulator
**         counter.
**     Parameters  : None
**     Returns     :
**         ---             - Content of the counter register.
** ===================================================================
*/
/*
word Puls1_GetCounterValue(void)

**      This method is implemented as macro. See Puls1.h file.      **
*/

/*
** ===================================================================
**     Method      :  Puls1_Init (bean PulseAccumulator)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
void Puls1_Init(void)
{
  /* PERT: PERT7=0*/
  clrReg8Bits(PERT, 0b10000000);               
  /* PACTL: ??=0,PAEN=0,PAMOD=0,PEDGE=0,CLK1=0,CLK0=0,PAOVI=0,PAI=0 */
  setReg8(PACTL, 0);                    
  /* TCTL1: OM7=0,OL7=0 */
  clrReg8Bits(TCTL1, 192);              
  /* PACNT: BIT15=0,BIT14=0,BIT13=0,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=0,BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg16(PACNT, 0);                   

  HPRIO = 218;                         /* Set vector with the highest priority */
  /* PACTL: ??=0,PAEN=0,PAMOD=0,PEDGE=1,CLK1=0,CLK0=0,PAOVI=0,PAI=1 */
  PACTL = 17;                          /* Set up pulse accumulator mode */
}

#pragma CODE_SEG __NEAR_SEG NON_BANKED     
/*
** ===================================================================
**     Method      :  Puls1_IntEdge (bean PulseAccumulator)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
ISR(Puls1_IntEdge)
{
  /* PAFLG: ??=0,??=0,??=0,??=0,??=0,??=0,PAOVF=0,PAIF=1 */
  PAFLG = 1;                           /* Reset request flag */
  Puls1_OnEdge();                      /* Invoke user event */
}

/* END Puls1. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.95.01 [03.62]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
