/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : TimerInt2ms.C
**     Project   : cntr_26_07
**     Processor : MC9S12GC32CFU16
**     Beantype  : TimerInt
**     Version   : Bean 02.151, Driver 01.16, CPU db: 2.87.392
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 26/11/2008, 15:25
**     Abstract  :
**         This bean "TimerInt" implements a periodic interrupt.
**         When the bean and its events are enabled, the "OnInterrupt"
**         event is called periodically with the period that you specify.
**         TimerInt supports also changing the period in runtime.
**         The source of periodic interrupt can be timer compare or reload
**         register or timer-overflow interrupt (of free running counter).
**     Settings  :
**         Timer name                  : TIM_Counter (16-bit)
**         Compare name                : TC7
**         Counter shared              : Yes
**
**         High speed mode
**             Prescaler               : divide-by-32
**             Clock                   : 500000 Hz
**           Initial period/frequency
**             Xtal ticks              : 16000
**             microseconds            : 2000
**             milliseconds            : 2
**             seconds (real)          : 0.0020000
**             Hz                      : 500
**
**         Runtime setting             : none
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : TCNT      [68]
**              Mode                   : TIOS      [64]
**              Run                    : TSCR1     [70]
**              Prescaler              : TSCR2     [77]
**
**         Compare registers
**              Compare                : TC7       [94]
**
**         Flip-flop registers
**              Mode                   : TCTL1     [72]
**     Contents  :
**         No public methods
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2007
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

/* MODULE TimerInt2ms. */

#include "timer_interrupt_2ms.h"
#include "TimerInt2ms.h"

#pragma DATA_SEG TimerInt2ms_DATA
#pragma CODE_SEG TimerInt2ms_CODE
#pragma CONST_SEG DEFAULT


/* Internal method prototypes */


/* End of Internal methods declarations */

/*
** ===================================================================
**     Method      :  timer_interrupt_2ms_Enable (bean TimerInt)
**
**     Description :
**         This method enables the bean - it starts the timer. Events
**         may be generated (<DisableEvent>/<EnableEvent>).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte timer_interrupt_2ms_Enable(void)
{
  //TC7 = TCNT + (word)1000;             /* Store new value to the compare register */ 
  TFLG1 = 128;                         /* Reset interrupt request flag */ 
  TIE_C7I = 1;                         /* Enable interrupt */ 
  return ERR_OK;                       /* OK */
}

byte timer_interrupt_2ms_Init(void){
  TC7 = TCNT + (word)1000; 
  return timer_interrupt_2ms_Enable(); 
}

/*
** ===================================================================
**     Method      :  timer_interrupt_2ms_Disable (bean TimerInt)
**
**     Description :
**         This method disables the bean - it stops the timer. No
**         events will be generated.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
/*
byte timer_interrupt_2ms_Disable(void)


/*lint -save -e718 -e746 -e937 -e957 -e18 -e516 -e532 -e14 Disable MISRA rule (71,72,25) checking. */
/*
** ===================================================================
**     Method      :  TimerInt2ms_Interrupt (bean TimerInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the bean.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(timer_interrupt_2ms_Interrupt)
{
  TC7 += (word)1000;                   /* Add value corresponding with periode */
  TFLG1 = 128;                         /* Reset interrupt request flag */
  TimerInt2ms_OnInterrupt();           /* Invoke user event */
}

#pragma CODE_SEG TimerInt2ms_CODE
/*lint -restore */

/* END TimerInt2ms. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.98 [03.98]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
