/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Cpu.C
**     Project   : contador_12_06_06
**     Processor : MC9S12GC16CFU16
**     Beantype  : MC9S12GC16_80
**     Version   : Bean 01.006, Driver 01.19.02, CPU db: 2.87.320
**     Datasheet : 9S12C128DGV1/D V01.05
**     Compiler  : Metrowerks HC12 C Compiler
**     Date/Time : 01/09/2008, 11:31 a.m.
**     Abstract  :
**         This bean "MC9S12GC16_80" implements properties, methods,
**         and events of the CPU.
**     Settings  :
**
**     Contents  :
**         EnableInt   - void Cpu_EnableInt(void);
**         DisableInt  - void Cpu_DisableInt(void);
**         SetWaitMode - void Cpu_SetWaitMode(void);
**         SetStopMode - void Cpu_SetStopMode(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2004
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

/* MODULE Cpu. */

#include "Display1.h"
#include "Display2.h"
#include "DL2.h"
#include "bits5ULN.h"
#include "vx1.h"
#include "vx2.h"
#include "trx.h"
#include "PTSL.h"
#include "PWSN.h"
#include "PUL.h"
#include "AS1.h"
#include "FLASH1.h"
#include "TI2.h"
#include "TI1.h"
#include "Rele1.h"
#include "Rele2.h"
#include "Reset.h"
#include "PP4.h"
#include "PP3.h"
#include "FreeCounter.h"
#include "Event.h"
#include "Events.h"
#include "Cpu.h"

#define CGM_DELAY  3327UL

#pragma DATA_SEG DEFAULT                                  

/* Global variables */
volatile byte CCR_reg;                 /* Current CCR reegister */
byte CpuMode = HIGH_SPEED;             /* Current speed mode */

/*Definition of global shadow variables*/
byte Shadow_M;


/*
** ===================================================================
**     Method      :  Cpu_Interrupt (bean MC9S12GC16_80)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
#pragma CODE_SEG __NEAR_SEG NON_BANKED     

ISR(Cpu_Interrupt)
{
}

#pragma CODE_SEG DEFAULT                                   

/*
** ===================================================================
**     Method      :  Cpu_DisableInt (bean MC9S12GC16_80)
**
**     Description :
**         Disable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (bean MC9S12GC16_80)
**
**     Description :
**         Enable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetStopMode (bean MC9S12GC16_80)
**
**     Description :
**         Set low power mode - Stop mode.
**         For more information about the stop mode see
**         documentation of this CPU.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetStopMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetWaitMode (bean MC9S12GC16_80)
**
**     Description :
**         Set low power mode - Wait mode.
**         For more information about the wait mode see
**         documentation of this CPU.
**         Release from Wait mode: Reset or interrupt
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetWaitMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  _EntryPoint (bean MC9S12GC16_80)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
extern void _Startup(void);            /* Forward declaration of external startup function declared in file Start12.c */
#pragma CODE_SEG __NEAR_SEG NON_BANKED     

#define INITRG_ADR  0x0011             /* Register map position register */

#pragma NO_FRAME
#pragma NO_EXIT
void _EntryPoint(void)
{
  /*** ### MC9S12GC16CFU16 "Cpu" init code ... ***/
  /*** PE initialization code after reset ***/
  /* Initialization of the registers INITRG, INITRM, INITEE is done to protect them to be written accidentally later by the application */
  *(byte*)INITRG_ADR = 0;              /* Set the register map position */
  asm("nop");                          /* nop instruction */
  INITRM=56;                           /* Set the RAM map position */
  /* MISC: ??=0,??=0,??=0,??=0,EXSTR1=1,EXSTR0=1,ROMHM=0,ROMON=1 */
  MISC=13;
  /* PEAR: NOACCE=0,??=0,PIPOE=0,NECLK=1,LSTRE=0,RDWE=0,??=0,??=0 */
  PEAR=16;
  CLKSEL = 0;                          /* Select clock source from XTAL and set bits in CLKSEL reg. */
  PLLCTL_PLLON = 0;                    /* Disable the PLL */
  SYNR = 24;                           /* Set the multiplier register */
  REFDV = 7;                           /* Set the divider register */
  /* PLLCTL: CME=0,PLLON=1,AUTO=1,ACQ=1,??=0,PRE=0,PCE=0,SCME=0 */
  PLLCTL = 112;
  while(!CRGFLG_LOCK) {};              /* Wait */
  CLKSEL_PLLSEL = 1;                   /* Select clock source from PLL */
  /*** End of PE initialization code after reset ***/
  __asm("jmp _Startup");               /* Jump to C startup code */
}

#pragma CODE_SEG DEFAULT                                   

/*
** ===================================================================
**     Method      :  PE_low_level_init (bean MC9S12GC16_80)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
void PE_low_level_init(void)
{
  /* Common initialization of the CPU registers */
  /* PORTA: BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg8(PORTA, 0);                    
  /* PUCR: PUPEE=0,PUPBE=0,PUPAE=0 */
  clrReg8Bits(PUCR, 19);                
  /* DDRA: BIT7=1,BIT6=1,BIT5=1,BIT4=1,BIT3=1,BIT2=1,BIT1=1,BIT0=1 */
  setReg8(DDRA, 255);                   
  /* PORTB: BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg8(PORTB, 0);                    
  /* DDRB: BIT7=1,BIT6=1,BIT5=1,BIT4=1,BIT3=1,BIT2=1,BIT1=1,BIT0=1 */
  setReg8(DDRB, 255);                   
  /* PIEJ: PIEJ7=0 */
  clrReg8Bits(PIEJ, 128);               
  /* PTJ: PTJ7=0 */
  clrReg8Bits(PTJ, 128);                
  /* PERJ: PERJ7=0 */
  clrReg8Bits(PERJ, 128);               
  /* DDRJ: DDRJ7=1 */
  setReg8Bits(DDRJ, 128);               
  /* PTM: PTM5=0,PTM4=0,PTM3=0,PTM2=0,PTM1=0,PTM0=0 */
  clrReg8Bits(PTM, 63);                 
  /* WOMM: WOMM5=0,WOMM4=0,WOMM3=0,WOMM2=0,WOMM1=0,WOMM0=0 */
  clrReg8Bits(WOMM, 63);                
  /* PERM: PERM5=0,PERM4=0,PERM3=0,PERM2=0,PERM1=0,PERM0=0 */
  clrReg8Bits(PERM, 63);                
  /* DDRM: DDRM5=1,DDRM4=1,DDRM3=1,DDRM2=1,DDRM1=1,DDRM0=1 */
  setReg8Bits(DDRM, 63);                
  /* PTS: PTS2=0 */
  clrReg8Bits(PTS, 4);                  
  /* WOMS: WOMS2=0 */
  clrReg8Bits(WOMS, 4);                 
  /* DDRS: DDRS2=1 */
  setReg8Bits(DDRS, 4);                 
  /* PTT: PTT1=0,PTT0=0 */
  clrReg8Bits(PTT, 3);                  
  /* PERT: PERT1=0,PERT0=0 */
  clrReg8Bits(PERT, 3);                 
  /* DDRT: DDRT1=1,DDRT0=1 */
  setReg8Bits(DDRT, 3);                 
  /* PEAR: RDWE=0 */
  clrReg8Bits(PEAR, 4);                 
  /* DDRE: BIT2=0 */
  clrReg8Bits(DDRE, 4);                 
  /* TSCR1: TEN=0,TSWAI=1,TSFRZ=1,TFFCA=0 */
  clrSetReg8Bits(TSCR1, 144, 96);       
  /* OC7M: OC7M2=0,OC7M0=0 */
  clrReg8Bits(OC7M, 5);                 
  /* TCTL2: OM2=0,OL2=0,OM1=0,OL1=0,OM0=0,OL0=0 */
  clrReg8Bits(TCTL2, 63);               
  /* TIE: C2I=0,C1I=0,C0I=0 */
  clrReg8Bits(TIE, 7);                  
  /* TIOS: IOS2=1,IOS1=1,IOS0=1 */
  setReg8Bits(TIOS, 7);                 
  /* TTOV: TOV2=0,TOV1=0,TOV0=0 */
  clrReg8Bits(TTOV, 7);                 
  /* TSCR2: TCRE=0,PR2=0,PR1=0,PR0=0 */
  clrReg8Bits(TSCR2, 15);               
  /* PIEP: PIEP5=0,PIEP1=0 */
  clrReg8Bits(PIEP, 34);                
  /* PTP: PTP5=0,PTP1=0 */
  clrReg8Bits(PTP, 34);                 
  /* PERP: PERP5=0,PERP1=0 */
  clrReg8Bits(PERP, 34);                
  /* DDRP: DDRP5=1,DDRP1=1 */
  setReg8Bits(DDRP, 34);                
  /* ATDDIEN: IEN1=1,IEN0=1 */
  setReg8Bits(ATDDIEN, 3);              
  /* PTAD: PTAD1=0,PTAD0=0 */
  clrReg8Bits(PTAD, 3);                 
  /* PERAD: PERAD1=0,PERAD0=0 */
  clrReg8Bits(PERAD, 3);                
  /* DDRAD: DDRAD1=1,DDRAD0=1 */
  setReg8Bits(DDRAD, 3);                
  /* PWMCTL: PSWAI=0,PFRZ=0 */
  clrReg8Bits(PWMCTL, 12);              
  /* PWMSDN: PWMIF=0,PWMIE=0,PWMRSTRT=0,PWMLVL=0,??=0,PWM5IN=0,PWM5INL=0,PWM5ENA=0 */
  setReg8(PWMSDN, 0);                   
  /* ### MC9S12GC16_80 "Cpu" init code ... */
  /* ### ByteIO "Display1" init code ... */
  /* ### ByteIO "Display2" init code ... */
  /* ### BitIO "DL2" init code ... */
  /* ### BitsIO "bits5ULN" init code ... */
  Shadow_M = 0;                        /* Initialize port shadow variable */
  /* ### InputPin "vx1" init code ... */
  /* ### InputPin "vx2" init code ... */
  /* ### BitIO "trx" init code ... */
  /* ### BitsIO "PTSL" init code ... */
  /* ### BitIO "PWSN" init code ... */
  /* ### InputPin "PUL" init code ... */
  /* ### Asynchro serial "AS1" init code ... */
  DDRS &= ~1;
  PTS |= 2;
  DDRS |= 2;
  AS1_Init();
  /* ### Init_FLASH "FLASH1" init code ... */
  FLASH1_Init();
  /* ### TimerInt "TI2" init code ... */
  TC2 = 25000;                         /* Store given value to the compare register */
  /* ### TimerInt "TI1" init code ... */
  HPRIO = 238;                         /* Set vector with the highest priority */
  TC0 = 625;                           /* Store given value to the compare register */
  /* ### BitIO "Rele1" init code ... */
  /* ### BitIO "Rele2" init code ... */
  /* ### InputPin "Reset" init code ... */
  /* ### BitIO "PP4" init code ... */
  /* ### BitIO "PP3" init code ... */
  /* ### Free running 32-bit counter "FreeCounter" init code ... */
  FreeCounter_Init();
 /* Common peripheral initialization - ENABLE */
  /* TSCR1: TEN=1 */
  setReg8Bits(TSCR1, 128);              
  INTCR_IRQEN = 0;                     /* Disable the IRQ interrupt. IRQ interrupt is enabled after CPU reset by default. */
  __EI();                              /* Enable interrupts */
}

/* END Cpu. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.95.01 [03.62]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
