/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : PUL.H
**     Project   : cntr_26_07
**     Processor : MC9S12GC32CFU16
**     Beantype  : InputPin
**     Version   : Bean 01.004, Driver 03.02, CPU db: 2.87.320
**     Compiler  : Metrowerks HC12 C Compiler
**     Date/Time : 11/10/2007, 10:11
**     Abstract  :
**
**     Settings  :
**
**     Contents  :
**         GetVal - bool PUL_GetVal(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2004
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef PUL_H_
#define PUL_H_

/* MODULE PUL. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma CODE_SEG PUL_CODE                     
/*
** ===================================================================
**     Method      :  PUL_GetVal (bean InputPin)
**
**     Description :
**         Returns the value of the Input bean. If direction is
**         [input] then reads the input value of the pin and returns
**         it.
**     Parameters  : None
**     Returns     :
**         ---             - Input value
** ===================================================================
*/
#define PUL_GetVal() ( \
    (getReg8(PTIS) & 8)                /* Evaluate to port raw data */ \
  )

#pragma CODE_SEG DEFAULT                                   

/* END PUL. */
#endif /* #ifndef __PUL_H_ */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.95.01 [03.62]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
