/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : RTI.H
**     Project   : LowCompsumption
**     Processor : MC9S12GC32CFU16
**     Beantype  : TimerInt
**     Version   : Bean 02.092, Driver 01.09, CPU db: 2.87.320
**     Compiler  : Metrowerks HC12 C Compiler
**     Date/Time : 31/01/2008, 11:11 a.m.
**     Abstract  :
**         This bean "TimerInt" implements a periodic interrupt.
**         When the bean and its events are enabled, the "OnInterrupt"
**         event is called periodically with the period that you specify.
**         TimerInt supports also changing the period in runtime.
**         The source of periodic interrupt can be timer compare or reload 
**         register or timer-overflow interrupt (of free running counter).
**     Settings  :
**         Timer name                  : RTICounter (1-bit)
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-16
**             Clock                   : 15 Hz
**           Initial period/frequency
**             Xtal ticks              : 1048576
**             microseconds            : 65536
**             milliseconds            : 66
**             seconds (real)          : 0.0655360
**             Hz                      : 15
**
**         Runtime setting             : none
**
**         Initialization:
**              Timer                  : Disabled
**              Events                 : Enabled
**
**         Timer registers
**              Mode                   : RTICTL    [59]
**              Run                    : RTICTL    [59]
**              Prescaler              : RTICTL    [59]
**
**         Compare registers
**
**         Flip-flop registers
**     Contents  :
**         Enable  - byte RTI_Enable(void);
**         Disable - byte RTI_Disable(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2004
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef __RTI
#define __RTI

/* MODULE RTI. */

#include "Cpu.h"
#include "OnRTI.h"


#pragma CODE_SEG RTI_CODE                     

#define RTI_Init() ( \
  setReg8(RTICTL, 127),                \
  ERR_OK                               /* Return result */ \
)


#define RTI_Enable() ( \
  CRGINT_RTIE = 1,                     /* Enable interrupt */ \
  ERR_OK                               /* Return result */ \
)
/*
** ===================================================================
**     Method      :  RTI_Enable (bean TimerInt)
**
**     Description :
**         Enables the bean - it starts the timer. Events may be
**         generated ("DisableEvent"/"EnableEvent").
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

#define RTI_Disable() ( \
  CRGINT_RTIE = 0,                     /* Disable interrupt */ \
  ERR_OK                               /* Return result */ \
)
/*
** ===================================================================
**     Method      :  RTI_Disable (bean TimerInt)
**
**     Description :
**         Disables the bean - it stops the timer. No events will be
**         generated.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

#pragma CODE_SEG DEFAULT                                   

/* END RTI. */

#endif /* ifndef __RTI */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.95.01 [03.62]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
