/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Display2.C
**     Project   : Funciones
**     Processor : MC9S08AC128CLK
**     Beantype  : BitsIO
**     Version   : Bean 02.097, Driver 03.17, CPU db: 3.00.021
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 05/12/2008, 9:02
**     Abstract  :
**         This bean "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**     Settings  :
**         Port name                   : PTD
**
**         Bit mask of the port        : $00FF
**         Number of bits/pins         : 8
**         Single bit numbers          : 0 to 7
**         Values range                : 0 to 255
**
**         Initial direction           : Output (direction can be changed)
**         Safe mode                   : yes
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         Port data register          : PTDD      [$0006]
**         Port control register       : PTDDD     [$0007]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    54   |   PTD0_AD1P8
**                    1      |    55   |   PTD1_AD1P9
**                    2      |    58   |   PTD2_KBI1P5_AD1P10
**                    3      |    59   |   PTD3_KBI1P6_AD1P11
**                    4      |    62   |   PTD4_TPM2CLK_AD1P12
**                    5      |    63   |   PTD5_AD1P13
**                    6      |    64   |   PTD6_TPM1CLK_AD1P14
**                    7      |    65   |   PTD7_KBI1P7_AD1P15
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents  :
**         GetDir    - bool Display2_GetDir(void);
**         SetDir    - void Display2_SetDir(bool Dir);
**         SetInput  - void Display2_SetInput(void);
**         SetOutput - void Display2_SetOutput(void);
**         GetVal    - byte Display2_GetVal(void);
**         PutVal    - void Display2_PutVal(byte Val);
**         GetBit    - bool Display2_GetBit(byte Bit);
**         PutBit    - void Display2_PutBit(byte Bit, bool Val);
**         SetBit    - void Display2_SetBit(byte Bit);
**         ClrBit    - void Display2_ClrBit(byte Bit);
**         NegBit    - void Display2_NegBit(byte Bit);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2008
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

/* MODULE Display2. */

#include "Display2.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  Display2_GetMsk (bean BitsIO)
**
**     Description :
**         The method returns a bit mask which corresponds to the 
**         required bit position.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static const  byte Display2_Table[8] = { /* Table of mask constants */
   0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80
};

static byte Display2_GetMsk (byte PinIndex)
{
  return (byte)(PinIndex<8 ? Display2_Table[PinIndex] : 0); /* Check range and return appropriate bit mask */
}

/*
** ===================================================================
**     Method      :  Display2_GetVal (bean BitsIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 255)
** ===================================================================
*/
byte Display2_GetVal(void)
{
  return (byte)(getReg8(PTDD) & 0xFF); /* Return port data */
}

/*
** ===================================================================
**     Method      :  Display2_PutVal (bean BitsIO)
**
**     Description :
**         This method writes the new output value.
**           a) direction = Input  : sets the new output value;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes the value to the
**                                   appropriate pins
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 255)
**     Returns     : Nothing
** ===================================================================
*/
void Display2_PutVal(byte Val)
{
  Val &= 0xFF;                         /* Mask output value */
  Shadow_PTD = Val;                    /* Set-up shadow variable */
  setReg8(PTDD, (getReg8(PTDD) & (~0xFF)) | Val); /* Put masked value on port */
}

/*
** ===================================================================
**     Method      :  Display2_GetBit (bean BitsIO)
**
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 7)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool Display2_GetBit(byte Bit)
{
  byte const Mask = Display2_GetMsk(Bit); /* Temporary variable - bit mask to test */
  return (bool)((getReg8(PTDD) & Mask) == Mask); /* Test if specified bit of port register is set */
}

/*
** ===================================================================
**     Method      :  Display2_PutBit (bean BitsIO)
**
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**           a) direction = Input  : sets the value of the specified
**                                   bit; this operation will be
**                                   shown on output after the
**                                   direction has been switched to
**                                   output (SetDir(TRUE);)
**           b) direction = Output : directly writes the value of the
**                                   bit to the appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 7)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
void Display2_PutBit(byte Bit, bool Val)
{
  byte const Mask = Display2_GetMsk(Bit); /* Temporary variable - put bit mask */
  if (Val) {
    setReg8Bits(PTDD, Mask);           /* [bit (Bit)]=0x01 */
    Shadow_PTD |= Mask;                /* Set appropriate bit in shadow variable */
  } else { /* !Val */
    clrReg8Bits(PTDD, Mask);           /* [bit (Bit)]=0x00 */
    Shadow_PTD &= ~Mask;               /* Clear appropriate bit in shadow variable */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  Display2_ClrBit (bean BitsIO)
**
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**           a) direction = Input  : sets the specified bit to "0";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   beenswitched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "0" to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 7)
**     Returns     : Nothing
** ===================================================================
*/
void Display2_ClrBit(byte Bit)
{
  byte const Mask = Display2_GetMsk(Bit); /* Temporary variable - set bit mask */
  clrReg8Bits(PTDD, Mask);             /* [bit (Bit)]=0x00 */
  Shadow_PTD &= ~Mask;                 /* Set appropriate bit in shadow variable */
}

/*
** ===================================================================
**     Method      :  Display2_SetBit (bean BitsIO)
**
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**           a) direction = Input  : sets the specified bit to "1";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "1" to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 7)
**     Returns     : Nothing
** ===================================================================
*/
void Display2_SetBit(byte Bit)
{
  byte const Mask = Display2_GetMsk(Bit); /* Temporary variable - set bit mask */
  setReg8Bits(PTDD, Mask);             /* [bit (Bit)]=0x01 */
  Shadow_PTD |= Mask;                  /* Set appropriate bit in shadow variable */
}

/*
** ===================================================================
**     Method      :  Display2_NegBit (bean BitsIO)
**
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**           a) direction = Input  : inverts the specified bit;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly inverts the value
**                                   of the appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
void Display2_NegBit(byte Bit)
{
  byte const Mask = Display2_GetMsk(Bit); /* Temporary variable - set bit mask */
  invertReg8Bits(PTDD, Mask);          /* [bit (Bit)]=invert */
  Shadow_PTD ^= Mask;                  /* Set appropriate bit in shadow variable */
}

/*
** ===================================================================
**     Method      :  Display2_GetDir (bean BitsIO)
**
**     Description :
**         This method returns direction of the bean.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the bean (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
** ===================================================================
*/
/*
bool Display2_GetDir(void)

**  This method is implemented as a macro. See Display2.h file.  **
*/

/*
** ===================================================================
**     Method      :  Display2_SetDir (bean BitsIO)
**
**     Description :
**         This method sets direction of the bean.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Dir        - Direction to set (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
**     Returns     : Nothing
** ===================================================================
*/
void Display2_SetDir(bool Dir)
{
  if (Dir) {
    setReg8(PTDD, (getReg8(PTDD) & (~0xFF)) | Shadow_PTD); /* Put masked value on port */
    /* PTDDD: PTDDD7=1,PTDDD6=1,PTDDD5=1,PTDDD4=1,PTDDD3=1,PTDDD2=1,PTDDD1=1,PTDDD0=1 */
    setReg8(PTDDD, 0xFF);               
  } else { /* !Dir */
    /* PTDDD: PTDDD7=0,PTDDD6=0,PTDDD5=0,PTDDD4=0,PTDDD3=0,PTDDD2=0,PTDDD1=0,PTDDD0=0 */
    setReg8(PTDDD, 0x00);               
  } /* !Dir */
}

/*
** ===================================================================
**     Method      :  Display2_SetOutput (bean BitsIO)
**
**     Description :
**         This method sets direction of the bean to output.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void Display2_SetOutput(void)
{
  setReg8(PTDD, (getReg8(PTDD) & (~0xFF)) | Shadow_PTD); /* Put masked value on port */
  /* PTDDD: PTDDD7=1,PTDDD6=1,PTDDD5=1,PTDDD4=1,PTDDD3=1,PTDDD2=1,PTDDD1=1,PTDDD0=1 */
  setReg8(PTDDD, 0xFF);                 
}

/*
** ===================================================================
**     Method      :  Display2_SetInput (bean BitsIO)
**
**     Description :
**         This method sets direction of the bean to input.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Display2_SetInput(void)

**  This method is implemented as a macro. See Display2.h file.  **
*/


/* END Display2. */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.03 [04.07]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
