#include "BoxPropiedadEntradaCondicional.hpp"

const struct BoxPropiedadEntradaCondicionalFactory boxPropiedadEntradaCondicionalFactory;
const struct BoxPropGetterEntradaCondicionalFactory boxPropGetterEntradaCondicionalFactory;