/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Bits5ULN.C
**     Project   : Funciones
**     Processor : MC9S08AC128CLK
**     Beantype  : BitsIO
**     Version   : Bean 02.097, Driver 03.17, CPU db: 3.00.021
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 05/12/2008, 9:10
**     Abstract  :
**         This bean "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**     Settings  :
**         Port name                   : PTJ
**
**         Bit mask of the port        : $003F
**         Number of bits/pins         : 6
**         Single bit numbers          : 0 to 5
**         Values range                : 0 to 63
**
**         Initial direction           : Output (direction can be changed)
**         Safe mode                   : yes
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         Port data register          : PTJD      [$001A]
**         Port control register       : PTJDD     [$001B]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    13   |   PTJ0
**                    1      |    14   |   PTJ1
**                    2      |    15   |   PTJ2
**                    3      |    16   |   PTJ3
**                    4      |    27   |   PTJ4
**                    5      |    28   |   PTJ5
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents  :
**         GetDir    - bool Bits5ULN_GetDir(void);
**         SetDir    - void Bits5ULN_SetDir(bool Dir);
**         SetInput  - void Bits5ULN_SetInput(void);
**         SetOutput - void Bits5ULN_SetOutput(void);
**         GetVal    - byte Bits5ULN_GetVal(void);
**         PutVal    - void Bits5ULN_PutVal(byte Val);
**         GetBit    - bool Bits5ULN_GetBit(byte Bit);
**         PutBit    - void Bits5ULN_PutBit(byte Bit, bool Val);
**         SetBit    - void Bits5ULN_SetBit(byte Bit);
**         ClrBit    - void Bits5ULN_ClrBit(byte Bit);
**         NegBit    - void Bits5ULN_NegBit(byte Bit);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2008
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

/* MODULE Bits5ULN. */

#include "Bits5ULN.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  Bits5ULN_GetMsk (bean BitsIO)
**
**     Description :
**         The method returns a bit mask which corresponds to the 
**         required bit position.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static const  byte Bits5ULN_Table[6] = { /* Table of mask constants */
   0x01, 0x02, 0x04, 0x08, 0x10, 0x20
};

static byte Bits5ULN_GetMsk (byte PinIndex)
{
  return (byte)(PinIndex<6 ? Bits5ULN_Table[PinIndex] : 0); /* Check range and return appropriate bit mask */
}

/*
** ===================================================================
**     Method      :  Bits5ULN_GetVal (bean BitsIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 63)
** ===================================================================
*/
byte Bits5ULN_GetVal(void)
{
  return (byte)(getReg8(PTJD) & 0x3F); /* Return port data */
}

/*
** ===================================================================
**     Method      :  Bits5ULN_PutVal (bean BitsIO)
**
**     Description :
**         This method writes the new output value.
**           a) direction = Input  : sets the new output value;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes the value to the
**                                   appropriate pins
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 63)
**     Returns     : Nothing
** ===================================================================
*/
void Bits5ULN_PutVal(byte Val)
{
  Val &= 0x3F;                         /* Mask output value */
  Shadow_PTJ = (byte)(Shadow_PTJ & ~0x3F | Val); /* Set-up shadow variable */
  setReg8(PTJD, (getReg8(PTJD) & (~0x3F)) | Val); /* Put masked value on port */
}

/*
** ===================================================================
**     Method      :  Bits5ULN_GetBit (bean BitsIO)
**
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 5)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool Bits5ULN_GetBit(byte Bit)
{
  byte const Mask = Bits5ULN_GetMsk(Bit); /* Temporary variable - bit mask to test */
  return (bool)((getReg8(PTJD) & Mask) == Mask); /* Test if specified bit of port register is set */
}

/*
** ===================================================================
**     Method      :  Bits5ULN_PutBit (bean BitsIO)
**
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**           a) direction = Input  : sets the value of the specified
**                                   bit; this operation will be
**                                   shown on output after the
**                                   direction has been switched to
**                                   output (SetDir(TRUE);)
**           b) direction = Output : directly writes the value of the
**                                   bit to the appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 5)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
void Bits5ULN_PutBit(byte Bit, bool Val)
{
  byte const Mask = Bits5ULN_GetMsk(Bit); /* Temporary variable - put bit mask */
  if (Val) {
    setReg8Bits(PTJD, Mask);           /* [bit (Bit)]=0x01 */
    Shadow_PTJ |= Mask;                /* Set appropriate bit in shadow variable */
  } else { /* !Val */
    clrReg8Bits(PTJD, Mask);           /* [bit (Bit)]=0x00 */
    Shadow_PTJ &= ~Mask;               /* Clear appropriate bit in shadow variable */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  Bits5ULN_ClrBit (bean BitsIO)
**
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**           a) direction = Input  : sets the specified bit to "0";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   beenswitched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "0" to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 5)
**     Returns     : Nothing
** ===================================================================
*/
void Bits5ULN_ClrBit(byte Bit)
{
  byte const Mask = Bits5ULN_GetMsk(Bit); /* Temporary variable - set bit mask */
  clrReg8Bits(PTJD, Mask);             /* [bit (Bit)]=0x00 */
  Shadow_PTJ &= ~Mask;                 /* Set appropriate bit in shadow variable */
}

/*
** ===================================================================
**     Method      :  Bits5ULN_SetBit (bean BitsIO)
**
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**           a) direction = Input  : sets the specified bit to "1";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "1" to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 5)
**     Returns     : Nothing
** ===================================================================
*/
void Bits5ULN_SetBit(byte Bit)
{
  byte const Mask = Bits5ULN_GetMsk(Bit); /* Temporary variable - set bit mask */
  setReg8Bits(PTJD, Mask);             /* [bit (Bit)]=0x01 */
  Shadow_PTJ |= Mask;                  /* Set appropriate bit in shadow variable */
}

/*
** ===================================================================
**     Method      :  Bits5ULN_NegBit (bean BitsIO)
**
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**           a) direction = Input  : inverts the specified bit;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly inverts the value
**                                   of the appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
void Bits5ULN_NegBit(byte Bit)
{
  byte const Mask = Bits5ULN_GetMsk(Bit); /* Temporary variable - set bit mask */
  invertReg8Bits(PTJD, Mask);          /* [bit (Bit)]=invert */
  Shadow_PTJ ^= Mask;                  /* Set appropriate bit in shadow variable */
}

/*
** ===================================================================
**     Method      :  Bits5ULN_GetDir (bean BitsIO)
**
**     Description :
**         This method returns direction of the bean.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the bean (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
** ===================================================================
*/
/*
bool Bits5ULN_GetDir(void)

**  This method is implemented as a macro. See Bits5ULN.h file.  **
*/

/*
** ===================================================================
**     Method      :  Bits5ULN_SetDir (bean BitsIO)
**
**     Description :
**         This method sets direction of the bean.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Dir        - Direction to set (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
**     Returns     : Nothing
** ===================================================================
*/
void Bits5ULN_SetDir(bool Dir)
{
  if (Dir) {
    setReg8(PTJD, (getReg8(PTJD) & (~0x3F)) | (Shadow_PTJ & 0x3F)); /* Put masked value on port */
    /* PTJDD: PTJDD5=1,PTJDD4=1,PTJDD3=1,PTJDD2=1,PTJDD1=1,PTJDD0=1 */
    setReg8Bits(PTJDD, 0x3F);           
  } else { /* !Dir */
    /* PTJDD: PTJDD5=0,PTJDD4=0,PTJDD3=0,PTJDD2=0,PTJDD1=0,PTJDD0=0 */
    clrReg8Bits(PTJDD, 0x3F);           
  } /* !Dir */
}

/*
** ===================================================================
**     Method      :  Bits5ULN_SetOutput (bean BitsIO)
**
**     Description :
**         This method sets direction of the bean to output.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void Bits5ULN_SetOutput(void)
{
  setReg8(PTJD, (getReg8(PTJD) & (~0x3F)) | (Shadow_PTJ & 0x3F)); /* Put masked value on port */
  /* PTJDD: PTJDD5=1,PTJDD4=1,PTJDD3=1,PTJDD2=1,PTJDD1=1,PTJDD0=1 */
  setReg8Bits(PTJDD, 0x3F);             
}

/*
** ===================================================================
**     Method      :  Bits5ULN_SetInput (bean BitsIO)
**
**     Description :
**         This method sets direction of the bean to input.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Bits5ULN_SetInput(void)

**  This method is implemented as a macro. See Bits5ULN.h file.  **
*/


/* END Bits5ULN. */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.03 [04.07]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
