/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Display1.C
**     Project   : Funciones
**     Processor : MC9S08AC128CLK
**     Beantype  : BitsIO
**     Version   : Bean 02.097, Driver 03.17, CPU db: 3.00.021
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 05/12/2008, 9:02
**     Abstract  :
**         This bean "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**     Settings  :
**         Port name                   : PTA
**
**         Bit mask of the port        : $00FF
**         Number of bits/pins         : 8
**         Single bit numbers          : 0 to 7
**         Values range                : 0 to 255
**
**         Initial direction           : Output (direction can be changed)
**         Safe mode                   : yes
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         Port data register          : PTAD      [$0000]
**         Port control register       : PTADD     [$0001]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    34   |   PTA0
**                    1      |    35   |   PTA1
**                    2      |    36   |   PTA2
**                    3      |    37   |   PTA3
**                    4      |    38   |   PTA4
**                    5      |    39   |   PTA5
**                    6      |    40   |   PTA6
**                    7      |    41   |   PTA7
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents  :
**         GetDir    - bool Display1_GetDir(void);
**         SetDir    - void Display1_SetDir(bool Dir);
**         SetInput  - void Display1_SetInput(void);
**         SetOutput - void Display1_SetOutput(void);
**         GetVal    - byte Display1_GetVal(void);
**         PutVal    - void Display1_PutVal(byte Val);
**         GetBit    - bool Display1_GetBit(byte Bit);
**         PutBit    - void Display1_PutBit(byte Bit, bool Val);
**         SetBit    - void Display1_SetBit(byte Bit);
**         ClrBit    - void Display1_ClrBit(byte Bit);
**         NegBit    - void Display1_NegBit(byte Bit);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2008
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

/* MODULE Display1. */

#include "Display1.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  Display1_GetMsk (bean BitsIO)
**
**     Description :
**         The method returns a bit mask which corresponds to the 
**         required bit position.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static const  byte Display1_Table[8] = { /* Table of mask constants */
   0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80
};

static byte Display1_GetMsk (byte PinIndex)
{
  return (byte)(PinIndex<8 ? Display1_Table[PinIndex] : 0); /* Check range and return appropriate bit mask */
}

/*
** ===================================================================
**     Method      :  Display1_GetVal (bean BitsIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 255)
** ===================================================================
*/
byte Display1_GetVal(void)
{
  return (byte)(getReg8(PTAD) & 0xFF); /* Return port data */
}

/*
** ===================================================================
**     Method      :  Display1_PutVal (bean BitsIO)
**
**     Description :
**         This method writes the new output value.
**           a) direction = Input  : sets the new output value;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes the value to the
**                                   appropriate pins
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 255)
**     Returns     : Nothing
** ===================================================================
*/
void Display1_PutVal(byte Val)
{
  Val &= 0xFF;                         /* Mask output value */
  Shadow_PTA = Val;                    /* Set-up shadow variable */
  setReg8(PTAD, (getReg8(PTAD) & (~0xFF)) | Val); /* Put masked value on port */
}

/*
** ===================================================================
**     Method      :  Display1_GetBit (bean BitsIO)
**
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 7)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool Display1_GetBit(byte Bit)
{
  byte const Mask = Display1_GetMsk(Bit); /* Temporary variable - bit mask to test */
  return (bool)((getReg8(PTAD) & Mask) == Mask); /* Test if specified bit of port register is set */
}

/*
** ===================================================================
**     Method      :  Display1_PutBit (bean BitsIO)
**
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**           a) direction = Input  : sets the value of the specified
**                                   bit; this operation will be
**                                   shown on output after the
**                                   direction has been switched to
**                                   output (SetDir(TRUE);)
**           b) direction = Output : directly writes the value of the
**                                   bit to the appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 7)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
void Display1_PutBit(byte Bit, bool Val)
{
  byte const Mask = Display1_GetMsk(Bit); /* Temporary variable - put bit mask */
  if (Val) {
    setReg8Bits(PTAD, Mask);           /* [bit (Bit)]=0x01 */
    Shadow_PTA |= Mask;                /* Set appropriate bit in shadow variable */
  } else { /* !Val */
    clrReg8Bits(PTAD, Mask);           /* [bit (Bit)]=0x00 */
    Shadow_PTA &= ~Mask;               /* Clear appropriate bit in shadow variable */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  Display1_ClrBit (bean BitsIO)
**
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**           a) direction = Input  : sets the specified bit to "0";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   beenswitched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "0" to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 7)
**     Returns     : Nothing
** ===================================================================
*/
void Display1_ClrBit(byte Bit)
{
  byte const Mask = Display1_GetMsk(Bit); /* Temporary variable - set bit mask */
  clrReg8Bits(PTAD, Mask);             /* [bit (Bit)]=0x00 */
  Shadow_PTA &= ~Mask;                 /* Set appropriate bit in shadow variable */
}

/*
** ===================================================================
**     Method      :  Display1_SetBit (bean BitsIO)
**
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**           a) direction = Input  : sets the specified bit to "1";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "1" to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 7)
**     Returns     : Nothing
** ===================================================================
*/
void Display1_SetBit(byte Bit)
{
  byte const Mask = Display1_GetMsk(Bit); /* Temporary variable - set bit mask */
  setReg8Bits(PTAD, Mask);             /* [bit (Bit)]=0x01 */
  Shadow_PTA |= Mask;                  /* Set appropriate bit in shadow variable */
}

/*
** ===================================================================
**     Method      :  Display1_NegBit (bean BitsIO)
**
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**           a) direction = Input  : inverts the specified bit;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly inverts the value
**                                   of the appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
void Display1_NegBit(byte Bit)
{
  byte const Mask = Display1_GetMsk(Bit); /* Temporary variable - set bit mask */
  invertReg8Bits(PTAD, Mask);          /* [bit (Bit)]=invert */
  Shadow_PTA ^= Mask;                  /* Set appropriate bit in shadow variable */
}

/*
** ===================================================================
**     Method      :  Display1_GetDir (bean BitsIO)
**
**     Description :
**         This method returns direction of the bean.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the bean (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
** ===================================================================
*/
/*
bool Display1_GetDir(void)

**  This method is implemented as a macro. See Display1.h file.  **
*/

/*
** ===================================================================
**     Method      :  Display1_SetDir (bean BitsIO)
**
**     Description :
**         This method sets direction of the bean.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Dir        - Direction to set (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
**     Returns     : Nothing
** ===================================================================
*/
void Display1_SetDir(bool Dir)
{
  if (Dir) {
    setReg8(PTAD, (getReg8(PTAD) & (~0xFF)) | Shadow_PTA); /* Put masked value on port */
    /* PTADD: PTADD7=1,PTADD6=1,PTADD5=1,PTADD4=1,PTADD3=1,PTADD2=1,PTADD1=1,PTADD0=1 */
    setReg8(PTADD, 0xFF);               
  } else { /* !Dir */
    /* PTADD: PTADD7=0,PTADD6=0,PTADD5=0,PTADD4=0,PTADD3=0,PTADD2=0,PTADD1=0,PTADD0=0 */
    setReg8(PTADD, 0x00);               
  } /* !Dir */
}

/*
** ===================================================================
**     Method      :  Display1_SetOutput (bean BitsIO)
**
**     Description :
**         This method sets direction of the bean to output.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void Display1_SetOutput(void)
{
  setReg8(PTAD, (getReg8(PTAD) & (~0xFF)) | Shadow_PTA); /* Put masked value on port */
  /* PTADD: PTADD7=1,PTADD6=1,PTADD5=1,PTADD4=1,PTADD3=1,PTADD2=1,PTADD1=1,PTADD0=1 */
  setReg8(PTADD, 0xFF);                 
}

/*
** ===================================================================
**     Method      :  Display1_SetInput (bean BitsIO)
**
**     Description :
**         This method sets direction of the bean to input.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Display1_SetInput(void)

**  This method is implemented as a macro. See Display1.h file.  **
*/


/* END Display1. */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.03 [04.07]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
