/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : bits2ULN.H
**     Project   : _12_10
**     Processor : MC9S12A64BCFU
**     Beantype  : BitsIO
**     Version   : Bean 02.065, Driver 03.04, CPU db: 2.87.268
**     Compiler  : Metrowerks HC12 C Compiler
**     Date/Time : 19/10/2005, 9:01
**     Abstract  :
**         This bean "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This bean is set to work in Output direction only.
**     Settings  :
**         Port name                   : J
**
**         Bit mask of the port        : 192
**         Number of bits/pins         : 2
**         Single bit numbers          : 0 to 1
**         Values range                : 0 to 3
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         Port data register          : PTJ       [616]
**         Port control register       : DDRJ      [618]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    69   |   PJ6_SDA_KWJ6
**                    1      |    68   |   PJ7_SCL_KWJ7
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents  :
**         PutVal - void bits2ULN_PutVal(byte Val);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2004
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef bits2ULN_H_
#define bits2ULN_H_

/* MODULE bits2ULN. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma CODE_SEG bits2ULN_CODE                     
/*
** ===================================================================
**     Method      :  bits2ULN_PutVal (bean BitsIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
#define bits2ULN_PutVal(Val) setReg8(PTJ, Val)

#pragma CODE_SEG DEFAULT                                   

/* END bits2ULN. */
#endif /* #ifndef __bits2ULN_H_ */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.95 [03.62]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
